"""Regenerate the C# test corpora from the model tables produced by build_lm.py.

Usage: python3 make_fixtures.py --ko-out out-ko --en-out out-en [--seed 20261009]
Reads the *shipped* tables (data/korean-lm.txt.gz · data/english-lm.txt), so copy the new tables into data/ first.
Writes tests/corpora/heldout-korean-1000.tsv, heldout-english-1000.tsv and scorer-fixtures.tsv.
tests/CoreTests.cs ScorerTests must then reproduce text+verdict exactly and llr within 0.05.
"""
import argparse, os, random, re, sys
sys.path.insert(0, os.path.dirname(__file__))
from detector import LanguageModel, Scorer

HERE = os.path.dirname(os.path.abspath(__file__))
HANAUTOMATA = os.path.dirname(os.path.dirname(HERE))
CORPORA = os.path.join(HANAUTOMATA, 'tests', 'corpora')
parser = argparse.ArgumentParser()
parser.add_argument('--ko-out', required=True, help='build_lm.py --out directory of the Korean corpus (heldout-korean.txt)')
parser.add_argument('--en-out', required=True, help='build_lm.py --out directory of the English corpus (heldout-english.txt)')
parser.add_argument('--seed', type=int, default=20261009)
args = parser.parse_args()
LETTERS = re.compile(r'^[a-z]{1,20}$')

lm = LanguageModel()
scorer = Scorer(lm)
# Design constants of src/Core.cs LanguageScorer (balanced preset).
scorer.T_KO = scorer.T_EN = 2.0; scorer.LEXICON_BONUS = 1.5; scorer.CONTINUITY = 1.5

ko = [l.rstrip('\n').split('\t') for l in open(os.path.join(args.ko_out, 'heldout-korean.txt'), encoding='utf-8') if l.strip()]
en = [l.rstrip('\n').split('\t') for l in open(os.path.join(args.en_out, 'heldout-english.txt'), encoding='utf-8') if l.strip()]
ko = [r for r in ko if LETTERS.match(r[0])]
en = [r for r in en if LETTERS.match(r[0])]
random.seed(args.seed)
random.shuffle(ko); random.shuffle(en)
ko_gate, ko_rest = ko[:1000], ko[1000:]
en_gate, en_rest = en[:1000], en[1000:]
with open(os.path.join(CORPORA, 'heldout-korean-1000.tsv'), 'w', encoding='utf-8') as f:
    f.write('# keys\tword\tcount — held-out Korean words (not in the hand lists) from the public corpus; gate: conversion >= 96%, wrong <= 0.5%\n')
    for k, w, c in ko_gate: f.write('%s\t%s\t%s\n' % (k, w, c))
with open(os.path.join(CORPORA, 'heldout-english-1000.tsv'), 'w', encoding='utf-8') as f:
    f.write('# word\tcount\tdict|nodict — held-out English tokens from the public corpus; gate: retention >= 97%, wrong <= 0.5%\n')
    for w, c, d in en_gate: f.write('%s\t%s\t%s\n' % (w, c, d))

rows = []
def add(raw, prev):
    previous = {'-': None, 'K': True, 'E': False}[prev]
    d = scorer.decide(raw, raw, previous)
    kind = 'K' if d.korean else ('U' if d.uncertain else 'E')
    rows.append((raw, raw, prev, d.text, kind, '%.2f' % d.llr))
for k, w, c in ko_rest[:350]: add(k, '-')
for k, w, c in ko_rest[350:450]: add(k, 'K')
for k, w, c in ko_rest[450:500]: add(k, 'E')
for w, c, d in en_rest[:350]: add(w, '-')
for w, c, d in en_rest[350:450]: add(w, 'E')
for w, c, d in en_rest[450:500]: add(w, 'K')
probes = ['go', 'so', 'do', 'no', 'dh', 'uk', 'ej', 'wbs', 'dj', 'rk', 'dl', 'rm', 'sj', 'emf', 'skdml', 'rmfjs', 'gksek', 'eogks',
          'report', 'flare', 'change', 'meeting', 'api', 'tjdqn', 'rhkwp', 'dkssudgktpdy', 'hello', 'world', 'gksms', 'rjt', 'figjam',
          'workauto', 'zh', 'eo', 'rms', 'dori', 'sudoku', 'plain', 'sksms', 'qksrkqtmqslek', 'ghldml', 'vmfhwprxm', 'for', 'gksrmf', 'zjavbxj']
for p in probes:
    for prev in '-KE': add(p, prev)
with open(os.path.join(CORPORA, 'scorer-fixtures.tsv'), 'w', encoding='utf-8') as f:
    f.write('# raw\tkeys\tprev(-|K|E)\texpectedText\tverdict(K|E|U)\tllr — generated by tests/lm/make_fixtures.py from the shipped tables; C# must reproduce text+verdict exactly and llr within 0.05\n')
    for r in rows: f.write('\t'.join(r) + '\n')
print('heldout korean %d english %d fixtures %d' % (len(ko_gate), len(en_gate), len(rows)))
